
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureFileCopy@3
  inputs:
    SourcePath: 'script.py'
    azureSubscription: 'Free Trial(475af040-27af-4db0-9bab-7ba87826c3a4)'
    Destination: 'AzureBlob'
    storage: 'vthanawalacontainer'
    ContainerName: 'mizuho'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
